<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lanjut</name>
   <tag></tag>
   <elementGuidId>5a5aee26-4c4f-4086-8457-437512a01313</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.introjs-button.introjs-nextbutton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='body']/div[26]/div/div[6]/a[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;body&quot;)/div[@class=&quot;introjs-tooltipReferenceLayer&quot;]/div[@class=&quot;introjs-tooltip introjs-floating&quot;]/div[@class=&quot;introjs-tooltipbuttons&quot;]/a[@class=&quot;introjs-button introjs-nextbutton&quot;][count(. | //a[@role = 'button' and @tabindex = '0' and @class = 'introjs-button introjs-nextbutton' and (text() = 'Lanjut' or . = 'Lanjut')]) = count(//a[@role = 'button' and @tabindex = '0' and @class = 'introjs-button introjs-nextbutton' and (text() = 'Lanjut' or . = 'Lanjut')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1b2938c6-74c1-429c-9a7c-2f2697917fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c3eb71c8-befb-4202-a885-05860a60b1be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8f579d8d-c9b2-457d-b436-cd0a9cc8c378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>introjs-button introjs-nextbutton</value>
      <webElementGuid>1b8297f5-bd0f-4243-9412-ccc4be6cc265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lanjut</value>
      <webElementGuid>927f5361-d88f-4a14-af2e-df95beff9862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;introjs-tooltipReferenceLayer&quot;]/div[@class=&quot;introjs-tooltip introjs-floating&quot;]/div[@class=&quot;introjs-tooltipbuttons&quot;]/a[@class=&quot;introjs-button introjs-nextbutton&quot;]</value>
      <webElementGuid>bb2eb149-d739-472c-ab3a-c690cd585ea0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body']/div[26]/div/div[6]/a[2]</value>
      <webElementGuid>8c824332-2dcb-4131-91db-b2609dcb84e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lanjut')]</value>
      <webElementGuid>91f73bb1-3bdc-4ef2-988d-a6876f8490df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[2]/following::a[1]</value>
      <webElementGuid>ce6a4669-5a8d-47c1-9a18-841364a4409c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selamat datang di CV-ME, berikut adalah panduan sederhana bagaimana cara membuat CV'])[1]/following::a[9]</value>
      <webElementGuid>45e48c5d-4c52-4a9b-9bcd-ede82319fe1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lanjut']/parent::*</value>
      <webElementGuid>eb308ac7-a6b1-492d-acbb-8bab131eb3d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a[2]</value>
      <webElementGuid>ba84c511-4bcc-4f7f-a2ea-c6ead18a1e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Lanjut' or . = 'Lanjut')]</value>
      <webElementGuid>35664bbc-2473-4778-97e4-5fb80d8554cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
