<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Selesai</name>
   <tag></tag>
   <elementGuidId>36d38c62-7e95-4982-8099-ec9c2eb50d31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.introjs-button.introjs-nextbutton.introjs-donebutton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='body']/div[26]/div/div[6]/a[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;body&quot;)/div[@class=&quot;introjs-tooltipReferenceLayer introjs-fixedTooltip&quot;]/div[@class=&quot;introjs-tooltip introjs-top-right-aligned&quot;]/div[@class=&quot;introjs-tooltipbuttons&quot;]/a[@class=&quot;introjs-button introjs-nextbutton introjs-donebutton&quot;][count(. | //a[@role = 'button' and @tabindex = '0' and @class = 'introjs-button introjs-nextbutton introjs-donebutton' and (text() = 'Selesai' or . = 'Selesai')]) = count(//a[@role = 'button' and @tabindex = '0' and @class = 'introjs-button introjs-nextbutton introjs-donebutton' and (text() = 'Selesai' or . = 'Selesai')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>417c9e23-8f9b-4cec-9e9a-5d737f8ecd0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>834a2f26-ecf4-4660-858c-767afa6de0bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cf152a63-f743-438d-b0c6-c54874e439b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>introjs-button introjs-nextbutton introjs-donebutton</value>
      <webElementGuid>de3ae34e-c0c6-4791-8238-e83c2b769d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selesai</value>
      <webElementGuid>90d94cb0-4e2e-42e9-ad0e-bb324b703d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;introjs-tooltipReferenceLayer introjs-fixedTooltip&quot;]/div[@class=&quot;introjs-tooltip introjs-top-right-aligned&quot;]/div[@class=&quot;introjs-tooltipbuttons&quot;]/a[@class=&quot;introjs-button introjs-nextbutton introjs-donebutton&quot;]</value>
      <webElementGuid>a21f3775-3f16-4cfc-b04e-d26dc409efbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body']/div[26]/div/div[6]/a[2]</value>
      <webElementGuid>f38ac615-a37c-46d3-aeb0-b30707211c70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Selesai')]</value>
      <webElementGuid>12cea611-abe2-4068-b9b1-d2fd08cc0dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[2]/following::a[1]</value>
      <webElementGuid>d42020c5-58f7-4f7f-b47b-e6525bdce5ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selain itu, Anda juga bisa membagikan CV Anda baik ke sosial media, maupun berupa link'])[1]/following::a[9]</value>
      <webElementGuid>017a1631-706e-4924-abac-eceea88ac44e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selesai']/parent::*</value>
      <webElementGuid>d39d7e20-b2f6-41a5-a402-cb2e3bd3fb0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a[2]</value>
      <webElementGuid>1ff61ff1-c34e-49d4-88ac-aebfc222638c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Selesai' or . = 'Selesai')]</value>
      <webElementGuid>50f0f866-a55a-49f2-8a69-e8ae7d786770</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
