<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_concat(id(, , body, , )divclass, , intr_3f128d</name>
   <tag></tag>
   <elementGuidId>3cbb5fd7-ac85-4918-9cd2-f794c05d2bbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='body']/div[24]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.introjs-overlay</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5b0019a9-ea9d-4219-ba7d-bab55098ac10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>introjs-overlay</value>
      <webElementGuid>7f4cecd7-0792-4590-a1bb-06b91d3a2d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;introjs-overlay&quot;]</value>
      <webElementGuid>f90eba52-1109-41c4-a658-d4552b38095a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body']/div[24]</value>
      <webElementGuid>2bcadf91-f206-4cd4-8f2a-1f9f60cbaa75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[24]</value>
      <webElementGuid>2610f7f8-1742-4137-b45d-0b1758574b91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
