<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Account Settings</name>
   <tag></tag>
   <elementGuidId>3f58ae68-d615-440d-9bc6-b5ab3d09680a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#w1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='w1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>02d37215-ef38-4f22-ad8e-a9ece9da058d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>w1</value>
      <webElementGuid>c0e8dd69-926c-4327-a420-3887d3bea253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn dropdown-toggle</value>
      <webElementGuid>607ed399-7786-40fa-908f-79dd52a6d079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>545983c8-eeb4-4126-ae3d-890d86d667c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Account Settings </value>
      <webElementGuid>54f3c5b7-b715-4516-a770-6def4c3d32d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w1&quot;)</value>
      <webElementGuid>f111bb41-0f3a-482b-bef6-58936f84f17c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='w1']</value>
      <webElementGuid>b48bda28-bc40-4918-86bd-46c00c679346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content-menu']/div/div/button</value>
      <webElementGuid>1b5842b4-f337-4cf1-8ea9-af1a32dd20a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kuesioner'])[1]/following::button[1]</value>
      <webElementGuid>0547aea9-02df-454a-81fb-d7d71e4f75a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Polling'])[1]/following::button[1]</value>
      <webElementGuid>126d2c77-d03f-4ca5-8c68-2aa05fb99e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Profile'])[1]/preceding::button[1]</value>
      <webElementGuid>cb6e2bdc-70fa-4557-b110-ce9ad32b84ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/preceding::button[1]</value>
      <webElementGuid>3b386e7c-6200-4c9a-8721-56fce4e5e5cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Account Settings']/parent::*</value>
      <webElementGuid>be4630ae-7f9b-4f9e-8160-23d9ae99c0d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>a78584b2-edaf-46fb-bd56-3f4a19753d84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'w1' and (text() = 'Account Settings ' or . = 'Account Settings ')]</value>
      <webElementGuid>6a819609-6169-4c3d-b164-91c6b77b73f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
