<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Login_fa fa-sign-in-alt</name>
   <tag></tag>
   <elementGuidId>4dde20cf-5cee-47ef-a262-61408021dbac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layoutLogin']/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-sign-in-alt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a217613c-e930-4d8e-b4c6-05ddf582c17c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-sign-in-alt</value>
      <webElementGuid>f274fcad-6f05-4609-8d66-b21da31628e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layoutLogin&quot;)/a[@class=&quot;btn btn-primary&quot;]/i[@class=&quot;fa fa-sign-in-alt&quot;]</value>
      <webElementGuid>01c36937-45f4-4d3a-8c89-f7185f321b52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layoutLogin']/a/i</value>
      <webElementGuid>615f0294-5c52-4ebc-ad41-661a1f0d5db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>8ae1dbcf-ad53-42e9-9bf3-a0f3ce547c1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
