<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Edit Profile_Profileavatar_url</name>
   <tag></tag>
   <elementGuidId>2bd14bed-2dcc-4204-b9de-d31156ed9daf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#profile-avatar_url</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile-avatar_url']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30339ad3-79df-4711-82df-75ecdb9431cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>1936bfad-073e-49b7-8cf0-6f5d945c82f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile-avatar_url</value>
      <webElementGuid>b52e2cf8-bd06-492b-a42b-81cb9004edb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Profile[avatar_url]</value>
      <webElementGuid>ab8a9b49-f5c1-4cef-a1e3-8e8e0888be23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>d46ba8f5066d08386fa15ad39bf17b57</value>
      <webElementGuid>fa218f5e-eda4-43af-b61c-df8f818a21e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0fb53226-f93d-47f5-be85-ae3fffb1a120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile-avatar_url&quot;)</value>
      <webElementGuid>83030e95-760b-493a-9b66-31288a32a71a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile-avatar_url']</value>
      <webElementGuid>ca88c3ed-f1fe-4d32-b404-e6777262881e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='image-upload-holder-body']/div/div/div/input[2]</value>
      <webElementGuid>5672704f-15d4-40df-95f1-b917f584d163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>42195640-7737-4775-8e62-296e7b07e3e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'profile-avatar_url' and @name = 'Profile[avatar_url]']</value>
      <webElementGuid>db11eb50-6c99-4b4f-a0de-efc2f292e7eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
